name:                     CI
on:                       [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        name:             [ubuntu-standard]
        include:
          - name:         ubuntu-standard
            os:           ubuntu-latest
    runs-on:              ${{ matrix.os }}
    steps:
    - uses:               actions/checkout@v1
    - name:               setup environment
      run: |
      sudo apt-get install openmpi-bin libopenmpi-dev
    - name:               build
      run:                |
        mkdir build ; cd build
        cmake .. -DCMAKE_CXX_COMPILER=mpicxx
        make VERBOSE=1
        cd ../
