name:                     CI
on:                       [push, pull_request]

jobs:
  build:
    steps:
    - uses:               actions/checkout@v1
    - name:               setup environment
      run: |
        sudo apt-get install openmpi-bin libopenmpi-dev
    - name:               build
      run:                |
        mkdir build ; cd build
        cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_CXX_FLAGS="-openmp"
        make VERBOSE=1
